apiVersion: v1
kind: Service
metadata:
  name: whatechchallenge-api-service
  labels:
    app: whatechchallenge-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: whatechchallenge-api-deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whatechchallenge-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whatechchallenge-api-deployment
    spec:
      containers:
      - name: whatechchallenge-api-instance
        image: randal/whatechchallenge-api
        ports:
        - containerPort: 80
        env:
        - name: Endpoints__CustomersEndpoint
          value: https://whatech-customerbets.azurewebsites.net/api/GetCustomers?code=ra4hpMmJYPeCXQAkyCVmmXOFFX7sM/oTiDzt7AY9eIeuUcDlTcb83A==&name=RandalVanceCunanan
        - name: Endpoints__BetsEndpoint
          value: https://whatech-customerbets.azurewebsites.net/api/GetBets?code=ra4hpMmJYPeCXQAkyCVmmXOFFX7sM/oTiDzt7AY9eIeuUcDlTcb83A==&name=RandalVanceCunanan
